AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  License: Apache-2.0
Description: "Launch template to avoid creating a custom ami"

Parameters:
  Project:
    Type: String

  VpcStackName:
    Type: String

  KmsKeyArn:
    Type: String

  ImageName:
    Type: String

  ImageTag:
    Type: String

Resources:
  ComputeEnvironment:
    Type: "AWS::Batch::ComputeEnvironment"
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub "${Project}-${AWS::Region}-${ImageTag}"
      ServiceRole: !Ref ServiceRole
      ComputeResources:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${VpcStackName}:SecurityGroup"
        Subnets:
          - Fn::ImportValue: !Sub "${VpcStackName}:SubnetA"
          - Fn::ImportValue: !Sub "${VpcStackName}:SubnetB"
        Type: EC2
        MinvCpus: 0
        MaxvCpus: 4
        #ImageId: ami-00921cd1ce43d567a # ami-0a6a36557ea3b9859
        InstanceRole: !Ref InstanceProfile
        InstanceTypes:
          - c5.large
        LaunchTemplate:
          LaunchTemplateId: !Ref ComputeLaunchTemplate
          Version: !GetAtt ComputeLaunchTemplate.LatestVersionNumber
        DesiredvCpus: 0
      State: ENABLED

  ComputeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Join ["-",[!Ref Project, "launch-template"]]
      LaunchTemplateData:
        KeyName: "eu-west-1"
        BlockDeviceMappings:
          - DeviceName:  '/dev/sdb'  # Amazon ECS-Optimized Amazon Linux 2 ami accepts EDS vol /dev/sd[b-l]
            Ebs:
              DeleteOnTermination: true
              Encrypted: false
              VolumeSize: 500
              VolumeType: "sc1"
        UserData:
         "Fn::Base64": !Sub |
            MIME-Version: 1.0
            Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

            --==MYBOUNDARY==
            Content-Type: text/x-shellscript; charset="us-ascii"

            #!/bin/bash
            mkfs.ext4  /dev/sdb
            (
            echo n # Add a new partition
            echo p # Primary partition
            echo 1 # Partition number
            echo   # First sector (Accept default: 1)
            echo   # Last sector (Accept default: varies)
            echo w # Write changes
            ) | fdisk  /dev/sdb
            mkfs.ext4  /dev/xvdb1
            mkdir /data
            echo " /dev/xvdb1       /data  ext4    defaults        0       2" >> /etc/fstab
            mount -a
            service docker restart

            yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            status amazon-ssm-agent
            start amazon-ssm-agent
            status amazon-ssm-agent

            --==MYBOUNDARY==

  JobDefinition:
    Type: "AWS::Batch::JobDefinition"
    Properties:
      Type: container
      Timeout:
        AttemptDurationSeconds: 1800
      JobDefinitionName: !Join ["-",[!Ref Project, "job-definition"]]
      ContainerProperties:
        Command :
          - "./../entrypoint.sh"
        Memory: 3500
        Privileged: false
        ReadonlyRootFilesystem: false
        Vcpus: 2
        Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}:${ImageTag}"
        MountPoints:
          - ContainerPath: "/workspace"
            ReadOnly: false
            SourceVolume: data
        Volumes:
          - Name: data
            Host:
              SourcePath: "/data"

  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref  ComputeEnvironment
      State: ENABLED
      Priority: 1
      JobQueueName: !Join ["-",[!Ref Project, "job-queue"]]

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Join ["-",[!Ref Project, "service-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "batch.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ecs-instance-options-3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ecs:CreateCluster"
                  - "ecs:DeregisterContainerInstance"
                  - "ecs:DiscoverPollEndpoint"
                  - "ecs:Poll"
                  - "ecs:RegisterContainerInstance"
                  - "ecs:StartTelemetrySession"
                  - "ecs:UpdateContainerInstancesState"
                  - "ecs:Submit*"
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:Get*"
                  - "s3:List*"
                Resource: "*"
        - PolicyName: "security"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                  - "kms:ReEncrypt"
                  - "kms:Describe"
                Resource: !Ref KmsKeyArn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Join ["-",[!Ref Project, "instance-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: "security"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                  - "kms:ReEncrypt"
                  - "kms:Describe"
                Resource: !Ref KmsKeyArn
        - PolicyName: ecs-instance-options
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ecs:CreateCluster"
                  - "ecs:DeregisterContainerInstance"
                  - "ecs:DiscoverPollEndpoint"
                  - "ecs:Poll"
                  - "ecs:RegisterContainerInstance"
                  - "ecs:StartTelemetrySession"
                  - "ecs:UpdateContainerInstancesState"
                  - "ecs:Submit*"
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:Get*"
                  - "s3:List*"
                Resource: "*"
        - PolicyName: "s3-glue-data"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:*"
                Resource:
                  - "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
